### ISSUE TITLE
About the role of C-PS

### ISSUE THREAD

**Issue by Deguello1** [boucadair/CATS-framework#17]
> The C-SMAs and C-NMAs share the collected information with CATS Path Selectors (C-PSes) that use such information to select the Egress CATS-Routers (and potentially the service instances) where to forward traffic for a given service demand

This wording suggests a somewhat limited role of C-PS (seemingly restricted to the selection of egress CATS-Routers), whereas the initial definition of a C-PS rather suggests path computation capabilities. I would therefore rephrase the above wording (by introducing the notion of path computation and selection besides the selection of egress CATS routers).

**Comment by VMatrix1900** [comment]
Here is the definition of C-PS: 
`CATS Path Selector (C-PS):
A computation logic that calculates and selects paths towards service locations and instances and which accommodates the requirements of service requests. Such a path computation engine takes into account the service and network status information.`

Path computation reminds me of PCE. I think the main part of computation in C-PS is more about selecting existing paths rather than calculate the path based on some requirements. It is also reflected in the name of C-PS(selector). Why does the definition of C-PS begin with "computation logic" while other definition begin with "an entity"?

**Comment by muzixing** [comment]
it seems that this issue can be closed.
